language: ruby
sudo: false
cache: bundler
rvm:
- 2.2.0
- 2.1.5
- 2.0.0-p598
- 1.9.3-p551
notifications:
  email: false
  irc:
    template:
    - '%{repository}/%{branch}/%{build_number}: %{message} -- %{build_url}'
    channels:
    - irc.oftc.net#akerl
